name: CI

on:
  pull_request:
  merge_group:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: bash
        run: |
          echo ${{ secrets.FOO }}
          if [ "${{ secrets.FOO }}" != "BAR" ]; then
            echo "Secret FOO is not set to 'bar'"
            exit 1
          fi
